# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [1]:
import numpy as np

In [2]:
# ejercicio 1 
a1 = np.array([1, 2, 3, 4])
print("¿Ninguno es cero?:", np.all(a1 != 0))

¿Ninguno es cero?: True


In [3]:
# ejercicio 2
a2 = np.array([0, 0, 2, 0])
print("¿Contiene algún elemento distinto de cero?:", np.any(a2 != 0))

¿Contiene algún elemento distinto de cero?: True


In [4]:
# ejercicio 3
a3 = np.array([1, 2, np.nan, np.inf])
print("¿Contiene NaN o Infinitos?:", np.isnan(a3) | np.isinf(a3))

¿Contiene NaN o Infinitos?: [False False  True  True]


In [5]:
# ejercicio 4
a4 = np.array([1, 2, np.inf])
print("¿Contiene valores infinitos?:", np.isinf(a4))

¿Contiene valores infinitos?: [False False  True]


In [6]:
# ejercicio 5
a5 = np.array([1, np.nan, 3])
print("¿Contiene valores NaN?:", np.isnan(a5))

¿Contiene valores NaN?: [False  True False]


In [7]:
# ejercicio 6
a_comp = np.array([1, 3, 5])
b_comp = np.array([2, 3, 4])
print("Mayor:", a_comp > b_comp)
print("Mayor o igual:", a_comp >= b_comp)
print("Menor:", a_comp < b_comp)
print("Menor o igual:", a_comp <= b_comp)

Mayor: [False False  True]
Mayor o igual: [False  True  True]
Menor: [ True False False]
Menor o igual: [ True  True False]


In [8]:
# ejercicio 7
a_mem = np.array([1, 7, 13, 105])
print(f"Memoria ocupada: {a_mem.nbytes} bytes")

Memoria ocupada: 32 bytes


In [9]:
# ejercicio 8
# Arreglo de 10 ceros
ceros = np.zeros(10)

# Arreglo de 10 unos
unos = np.ones(10)

# Arreglo de 10 cincos (multiplicamos el arreglo de unos por 5)
cincos = np.ones(10) * 5

print("Ceros:", ceros)
print("Unos:", unos)
print("Cincos:", cincos)

Ceros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Unos: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Cincos: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [10]:
# ejercicio 9 
arreglo_30_70 = np.arange(30, 71)
print(arreglo_30_70)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [11]:
# ejercicio 10
arreglo_pares_30_70 = np.arange(30, 71, 2)
print(arreglo_pares_30_70)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [12]:
# ejercicio 11
matriz_identidad = np.eye(3)
print(matriz_identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# ejercicio 12
numero_aleatorio = np.random.rand()
print(numero_aleatorio)

0.5500769801212838


In [23]:
# ejercicio 13
arreglo_normal = np.random.randn(15)

print(arreglo_normal)

[ 0.83120846  1.02309628  0.22548627 -0.78965265  1.38050128  0.9950746
  0.96493596  0.7214697  -1.34187303 -1.67784201  0.03852663  0.00745406
 -0.26388686 -1.05957901 -0.73117886]


In [15]:
# ejercicio 14
arreglo = np.arange(15, 56)
resultado = arreglo[1:-1]

print(resultado)

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [16]:
# ejercicio 15
vector_equitativo = np.linspace(5, 50, 10)

print(vector_equitativo)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [17]:
# ejercicio 16
vector = np.arange(21)
vector[(vector >= 9) & (vector <= 15)] *= -1

print(vector)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [18]:
# ejercicio 17
a = np.array([1, 2, 3])
# Convertimos a lista
lista_python = a.tolist()

print(lista_python)
print(type(lista_python))

[1, 2, 3]
<class 'list'>


In [19]:
# ejercicio 18
l = [1, 2, 3]

# Convertimos a arreglo de Numpy
a = np.array(l)

print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [20]:
# ejercicio 19
m = np.array([[1, 2], [3, 4]])
m_pares = (m % 2 == 0)

print("Matriz original:\n", m)
print("\nMatriz de resultados (¿Es par?):\n", m_pares)

Matriz original:
 [[1 2]
 [3 4]]

Matriz de resultados (¿Es par?):
 [[False  True]
 [False  True]]


In [21]:
# ejercicio 20
m = np.array([[1, 2, 3], [4, 5, 6]])

# Obtenemos las dimensiones
filas, columnas = m.shape

print(f"La matriz tiene {filas} filas y {columnas} columnas.")

La matriz tiene 2 filas y 3 columnas.
